uurl = "http://localhost:8080/"
use_ssl = False
auth_root = "auth/"
cert_file = "unveillance_web.crt"
key_file = "unveillance_web.key"
assets_path = ""
server_port = 8888
cookie_tag = "uv-cookie-tag"
cookie_secret = "this is the secret"
no_access_cookie = "uv-cookie-noaccess"
